### PR TITLE
10_update_readme@main: Updated readme with pilot3 info.

### PR DESCRIPTION
**Pull request by DeclanHodges**
New pilot3 readme:
image
image
image

Note that file structure is based on new structure in PR #9.

### CODE REVIEW

**Comment by DeclanHodges** [comment]
This may already be planned, but I think we should update the TLF programs/output naming conventions to match (i.e. the code and output file both or neither should include the "-pilot3" suffix):
image

**Comment by laxamanaj** [comment]
Thanks for creating this PR, @DeclanHodges .

I've added @zhaol30 , Lei Zhao, as a reviewer and I just sent Phani and invite to join.  I'm fine if Lei, approves this as well.

**Review by laxamanaj — APPROVED** [review]
Thanks for this update, @DeclanHodges !

**Comment by robertdevine** [comment]
Thanks @laxamanaj and @DeclanHodges. It appears pandoc will also convert from rtf to pdf. Don't quite have the syntax yet to include the headers and tlf labels (but pretty cool)! We use Haskell at J&J for many years. Looks like Posit Cloud includes pandoc in each cloud space. Might be another alternative for programmatic format conversion. Thanks again.
10_update_readme

**Pull request merged**
